FROM python:3.12-slim

ARG APP_VERSION=1.0.0
ARG BUILD_DATE

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app.py .

ENV APP_VERSION=${APP_VERSION}

LABEL build_date=${BUILD_DATE}
LABEL version=${APP_VERSION}

CMD ["python", "app.py"]
