apiVersion: v1
kind: Pod
metadata:
  name: api-env-demo
spec:
  containers:
    - name: api
      image: alpine
      command: ["sh", "-c", "env | grep -E 'APP_|ENVIRONMENT|LOG_|DB_' && sleep 3600"]
      envFrom:
        - configMapRef:
            name: task-api-config
