apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  DB_USER: YWRtaW4=
  DB_PASSWORD: cEBzc3cwcmQh
---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets-easy
type: Opaque
stringData:
  DB_USER: admin
  DB_PASSWORD: "p@ssw0rd!"
  API_KEY: "my-secret-api-key"
